# Validação

In [5]:
from pathlib import Path

from reporting.cross_validation import (
    load_and_display_cross_validation_statistics,
)

In [6]:
artifact_directory = Path("_artifacts") / "genis"

## Decision Tree

In [7]:
load_and_display_cross_validation_statistics(
    artifact_directory / "decision_tree",
)

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,1cbc00d06004,passthrough,gini,20.0,2,1,0.999881,0.999823,0.999806,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004
1,98aa19114822,passthrough,gini,NaN,2,1,0.999881,0.999823,0.999806,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004
2,1f2e9955a969,passthrough,gini,20.0,5,1,0.999874,0.999811,0.999806,0.99994 ± 0.00001,0.99983 ± 0.00003,0.99983 ± 0.00005,0.99983 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99982 ± 0.00004,0.99983 ± 0.00005
3,5b7f649f2af0,passthrough,gini,NaN,5,1,0.999874,0.999811,0.999806,0.99994 ± 0.00001,0.99983 ± 0.00003,0.99983 ± 0.00005,0.99983 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99982 ± 0.00004,0.99983 ± 0.00005
4,03ff75232577,random_over_sampler,gini,20.0,5,1,0.999852,0.999741,0.999853,0.99994 ± 0.00001,0.99983 ± 0.00006,0.99980 ± 0.00007,0.99982 ± 0.00006,0.99989 ± 0.00003,0.99964 ± 0.00013,0.99984 ± 0.00004,0.99980 ± 0.00007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,e49f974c2959,passthrough,entropy,NaN,10,5,0.999618,0.999645,0.999592,0.99987 ± 0.00001,0.99963 ± 0.00004,0.99961 ± 0.00002,0.99962 ± 0.00003,0.99986 ± 0.00001,0.99958 ± 0.00004,0.99962 ± 0.00003,0.99961 ± 0.00002
68,eb1b7735c06a,passthrough,entropy,NaN,5,5,0.999618,0.999645,0.999592,0.99987 ± 0.00001,0.99963 ± 0.00004,0.99961 ± 0.00002,0.99962 ± 0.00003,0.99986 ± 0.00001,0.99958 ± 0.00004,0.99962 ± 0.00003,0.99961 ± 0.00002
69,497adfad464f,passthrough,gini,10.0,10,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001
70,a55c9887c1a2,passthrough,gini,10.0,5,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001
71,c55590c695f3,passthrough,gini,10.0,2,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001

,configuration_id,seed,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,passthrough,gini,10.0,2,1,0.999830,0.999846,0.999428,0.999637,0.999645,0.999362,0.999506,0.999428
1,f555fc62ae6a,32,passthrough,gini,10.0,2,1,0.999827,0.999844,0.999396,0.999620,0.999589,0.999286,0.999496,0.999396
2,f555fc62ae6a,59,passthrough,gini,10.0,2,1,0.999817,0.999832,0.999392,0.999612,0.999614,0.999302,0.999466,0.999392
3,c55590c695f3,27,passthrough,gini,10.0,2,5,0.999813,0.999777,0.999381,0.999579,0.999633,0.999318,0.999456,0.999381
4,c55590c695f3,32,passthrough,gini,10.0,2,5,0.999820,0.999821,0.999394,0.999607,0.999588,0.999275,0.999476,0.999394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,d5925f8116be,32,random_over_sampler,entropy,NaN,10,1,0.999922,0.999768,0.999704,0.999736,0.999830,0.999491,0.999773,0.999704
212,d5925f8116be,59,random_over_sampler,entropy,NaN,10,1,0.999895,0.999665,0.999658,0.999661,0.999803,0.999349,0.999694,0.999658
213,5a7ac466ea55,27,random_over_sampler,entropy,NaN,10,5,0.999925,0.999785,0.999743,0.999764,0.999852,0.999571,0.999782,0.999743
214,5a7ac466ea55,32,random_over_sampler,entropy,NaN,10,5,0.999915,0.999734,0.999712,0.999723,0.999838,0.999503,0.999753,0.999712
215,5a7ac466ea55,59,random_over_sampler,entropy,NaN,10,5,0.999881,0.999598,0.999648,0.999623,0.999802,0.999299,0.999654,0.999648

,configuration_id,seed,fold,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,1,passthrough,gini,10.0,2,1,0.999827,0.999884,0.999444,0.999664,0.999644,0.999377,0.999496,0.999444
1,f555fc62ae6a,27,2,passthrough,gini,10.0,2,1,0.999827,0.999768,0.999427,0.999597,0.999616,0.999279,0.999496,0.999427
2,f555fc62ae6a,27,3,passthrough,gini,10.0,2,1,0.999837,0.999886,0.999413,0.999649,0.999675,0.999429,0.999525,0.999413
3,f555fc62ae6a,32,1,passthrough,gini,10.0,2,1,0.999878,0.999882,0.999569,0.999726,0.999705,0.999482,0.999644,0.999569
4,f555fc62ae6a,32,2,passthrough,gini,10.0,2,1,0.999837,0.999852,0.999448,0.999649,0.999635,0.999345,0.999525,0.999448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,5a7ac466ea55,32,2,random_over_sampler,entropy,NaN,10,5,0.999949,0.999873,0.999841,0.999857,0.999907,0.999762,0.999852,0.999841
644,5a7ac466ea55,32,3,random_over_sampler,entropy,NaN,10,5,0.999878,0.999610,0.999530,0.999570,0.999734,0.999171,0.999644,0.999530
645,5a7ac466ea55,59,1,random_over_sampler,entropy,NaN,10,5,0.999888,0.999649,0.999564,0.999607,0.999757,0.999242,0.999674,0.999564
646,5a7ac466ea55,59,2,random_over_sampler,entropy,NaN,10,5,0.999837,0.999455,0.999664,0.999559,0.999795,0.999160,0.999526,0.999664
647,5a7ac466ea55,59,3,random_over_sampler,entropy,NaN,10,5,0.999919,0.999689,0.999717,0.999703,0.999853,0.999496,0.999763,0.999717

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,1cbc00d06004,passthrough,gini,20.0,2,1,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004

## Random Forest

In [8]:
load_and_display_cross_validation_statistics(
    artifact_directory / "random_forest",
)

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,7eb62a443ff7,passthrough,200,NaN,2,1,0.999944,0.999923,0.999917,0.99998 ± 0.00001,0.99995 ± 0.00001,0.99990 ± 0.00002,0.99993 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99993 ± 0.00002,0.99990 ± 0.00002
1,092fc645be1f,passthrough,100,NaN,2,1,0.999929,0.999938,0.999911,0.99998 ± 0.00001,0.99995 ± 0.00001,0.99990 ± 0.00002,0.99993 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99993 ± 0.00002,0.99990 ± 0.00002
2,a527f6806362,passthrough,200,20.0,2,1,0.999935,0.999923,0.999917,0.99998 ± 0.00000,0.99995 ± 0.00001,0.99990 ± 0.00001,0.99993 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99993 ± 0.00001,0.99990 ± 0.00001
3,18ddbe67ac64,passthrough,100,20.0,2,1,0.999929,0.999909,0.999925,0.99997 ± 0.00000,0.99995 ± 0.00002,0.99989 ± 0.00001,0.99992 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99992 ± 0.00001,0.99989 ± 0.00001
4,daabcb4ba546,passthrough,200,20.0,10,1,0.999909,0.999902,0.999938,0.99997 ± 0.00001,0.99994 ± 0.00002,0.99989 ± 0.00002,0.99992 ± 0.00002,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99992 ± 0.00002,0.99989 ± 0.00002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,4440f03b62d1,passthrough,200,10.0,10,5,0.999596,0.999603,0.999704,0.99985 ± 0.00002,0.99976 ± 0.00004,0.99951 ± 0.00008,0.99963 ± 0.00006,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99957 ± 0.00006,0.99951 ± 0.00008
68,f5a1a7cebdb4,passthrough,200,10.0,5,5,0.999596,0.999603,0.999704,0.99985 ± 0.00002,0.99976 ± 0.00004,0.99951 ± 0.00008,0.99963 ± 0.00006,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99957 ± 0.00006,0.99951 ± 0.00008
69,111a8e359681,passthrough,100,10.0,5,5,0.999592,0.999572,0.999646,0.99984 ± 0.00001,0.99974 ± 0.00004,0.99947 ± 0.00005,0.99960 ± 0.00004,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99953 ± 0.00002,0.99947 ± 0.00005
70,96d78ba03017,passthrough,100,10.0,10,5,0.999592,0.999572,0.999646,0.99984 ± 0.00001,0.99974 ± 0.00004,0.99947 ± 0.00005,0.99960 ± 0.00004,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99953 ± 0.00002,0.99947 ± 0.00005
71,c3125a46f515,passthrough,100,10.0,2,5,0.999592,0.999572,0.999646,0.99984 ± 0.00001,0.99974 ± 0.00004,0.99947 ± 0.00005,0.99960 ± 0.00004,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99953 ± 0.00002,0.99947 ± 0.00005

,configuration_id,seed,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,df61f3a5c0de,27,passthrough,100,10.0,2,1,0.999915,0.999942,0.999689,0.999816,1.0,1.000000,0.999753,0.999689
1,df61f3a5c0de,32,passthrough,100,10.0,2,1,0.999915,0.999936,0.999695,0.999816,1.0,1.000000,0.999753,0.999695
2,df61f3a5c0de,59,passthrough,100,10.0,2,1,0.999905,0.999939,0.999654,0.999797,1.0,1.000000,0.999723,0.999654
3,c3125a46f515,27,passthrough,100,10.0,2,5,0.999841,0.999697,0.999488,0.999592,1.0,0.999999,0.999535,0.999488
4,c3125a46f515,32,passthrough,100,10.0,2,5,0.999830,0.999730,0.999414,0.999572,1.0,0.999999,0.999506,0.999414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,976588e868ef,32,random_over_sampler,200,NaN,10,1,0.999969,0.999932,0.999873,0.999903,1.0,1.000000,0.999911,0.999873
212,976588e868ef,59,random_over_sampler,200,NaN,10,1,0.999966,0.999915,0.999862,0.999888,1.0,1.000000,0.999901,0.999862
213,03948c1c012b,27,random_over_sampler,200,NaN,10,5,0.999976,0.999929,0.999902,0.999915,1.0,1.000000,0.999931,0.999902
214,03948c1c012b,32,random_over_sampler,200,NaN,10,5,0.999976,0.999951,0.999896,0.999923,1.0,1.000000,0.999931,0.999896
215,03948c1c012b,59,random_over_sampler,200,NaN,10,5,0.999963,0.999898,0.999850,0.999874,1.0,1.000000,0.999891,0.999850

,configuration_id,seed,fold,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,df61f3a5c0de,27,1,passthrough,100,10.0,2,1,0.999919,0.999943,0.999706,0.999825,1.0,1.0,0.999763,0.999706
1,df61f3a5c0de,27,2,passthrough,100,10.0,2,1,0.999939,0.999981,0.999775,0.999878,1.0,1.0,0.999822,0.999775
2,df61f3a5c0de,27,3,passthrough,100,10.0,2,1,0.999888,0.999902,0.999585,0.999744,1.0,1.0,0.999674,0.999585
3,df61f3a5c0de,32,1,passthrough,100,10.0,2,1,0.999898,0.999968,0.999637,0.999803,1.0,1.0,0.999703,0.999637
4,df61f3a5c0de,32,2,passthrough,100,10.0,2,1,0.999919,0.999926,0.999724,0.999825,1.0,1.0,0.999763,0.999724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,03948c1c012b,32,2,random_over_sampler,200,NaN,10,5,0.999969,0.999959,0.999879,0.999919,1.0,1.0,0.999911,0.999879
644,03948c1c012b,32,3,random_over_sampler,200,NaN,10,5,0.999980,0.999931,0.999896,0.999913,1.0,1.0,0.999941,0.999896
645,03948c1c012b,59,1,random_over_sampler,200,NaN,10,5,0.999959,0.999907,0.999844,0.999876,1.0,1.0,0.999881,0.999844
646,03948c1c012b,59,2,random_over_sampler,200,NaN,10,5,0.999990,0.999997,0.999965,0.999981,1.0,1.0,0.999970,0.999965
647,03948c1c012b,59,3,random_over_sampler,200,NaN,10,5,0.999939,0.999789,0.999740,0.999765,1.0,1.0,0.999822,0.999740

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,7eb62a443ff7,passthrough,200,NaN,2,1,0.99998 ± 0.00001,0.99995 ± 0.00001,0.99990 ± 0.00002,0.99993 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99993 ± 0.00002,0.99990 ± 0.00002

## XGBoost

In [9]:
load_and_display_cross_validation_statistics(
    artifact_directory / "xgboost",
)

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,17edbfb766e1,passthrough,200,6,0.10,1,0.8,0.999900,0.999908,0.999885,0.99997 ± 0.00000,0.99991 ± 0.00002,0.99989 ± 0.00001,0.99990 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99991 ± 0.00001,0.99989 ± 0.00001
1,ce27fc414a86,passthrough,200,6,0.10,1,1.0,0.999888,0.999908,0.999885,0.99997 ± 0.00000,0.99990 ± 0.00002,0.99988 ± 0.00001,0.99989 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99990 ± 0.00001,0.99988 ± 0.00001
2,111261f0b5d1,passthrough,200,3,0.10,1,1.0,0.999859,0.999909,0.999909,0.99997 ± 0.00001,0.99990 ± 0.00003,0.99988 ± 0.00003,0.99989 ± 0.00003,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99991 ± 0.00002,0.99988 ± 0.00003
3,4d7c3d4f1e67,random_over_sampler,200,3,0.10,1,1.0,0.999866,0.999901,0.999893,0.99997 ± 0.00001,0.99988 ± 0.00003,0.99989 ± 0.00001,0.99989 ± 0.00002,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99991 ± 0.00002,0.99989 ± 0.00001
4,fe6333417938,random_over_sampler,200,3,0.10,1,0.8,0.999851,0.999880,0.999907,0.99997 ± 0.00001,0.99987 ± 0.00004,0.99989 ± 0.00002,0.99988 ± 0.00003,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99990 ± 0.00002,0.99989 ± 0.00002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,0afd3dd057f0,random_over_sampler,100,3,0.05,5,0.8,0.999246,0.999332,0.999269,0.99979 ± 0.00001,0.99925 ± 0.00007,0.99931 ± 0.00003,0.99928 ± 0.00004,0.99999 ± 0.00000,0.99992 ± 0.00001,0.99937 ± 0.00002,0.99931 ± 0.00003
60,693e0b59ff1a,random_over_sampler,100,3,0.05,5,1.0,0.999261,0.999275,0.999280,0.99978 ± 0.00001,0.99924 ± 0.00002,0.99930 ± 0.00003,0.99927 ± 0.00001,0.99999 ± 0.00000,0.99992 ± 0.00001,0.99937 ± 0.00002,0.99930 ± 0.00003
61,74217161e39c,random_over_sampler,100,3,0.05,1,1.0,0.999261,0.999289,0.999254,0.99978 ± 0.00000,0.99924 ± 0.00004,0.99930 ± 0.00001,0.99927 ± 0.00002,0.99999 ± 0.00000,0.99993 ± 0.00001,0.99936 ± 0.00001,0.99930 ± 0.00001
62,67b9757d8abd,passthrough,100,3,0.05,5,0.8,0.999276,0.999209,0.999283,0.99976 ± 0.00001,0.99932 ± 0.00003,0.99919 ± 0.00005,0.99926 ± 0.00004,1.00000 ± 0.00000,0.99996 ± 0.00001,0.99931 ± 0.00004,0.99919 ± 0.00005
63,8b5a5ba3eeec,passthrough,100,3,0.05,5,1.0,0.999270,0.999223,0.999243,0.99976 ± 0.00001,0.99932 ± 0.00002,0.99917 ± 0.00003,0.99925 ± 0.00002,1.00000 ± 0.00000,0.99996 ± 0.00000,0.99929 ± 0.00002,0.99917 ± 0.00003

,configuration_id,seed,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f3ea52a0aee0,27,passthrough,100,3,0.05,1,0.8,0.999793,0.999398,0.999295,0.999346,0.999998,0.999967,0.999397,0.999295
1,f3ea52a0aee0,32,passthrough,100,3,0.05,1,0.8,0.999780,0.999345,0.999249,0.999297,0.999999,0.999982,0.999357,0.999249
2,f3ea52a0aee0,59,passthrough,100,3,0.05,1,0.8,0.999790,0.999369,0.999283,0.999326,0.999999,0.999979,0.999387,0.999283
3,c85e973cb979,27,passthrough,100,3,0.05,1,1.0,0.999793,0.999398,0.999295,0.999346,0.999998,0.999966,0.999397,0.999295
4,c85e973cb979,32,passthrough,100,3,0.05,1,1.0,0.999797,0.999383,0.999307,0.999344,0.999999,0.999989,0.999407,0.999307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,333beb896e6e,32,random_over_sampler,200,6,0.10,5,0.8,0.999956,0.999829,0.999845,0.999837,1.000000,0.999999,0.999871,0.999845
188,333beb896e6e,59,random_over_sampler,200,6,0.10,5,0.8,0.999953,0.999818,0.999827,0.999823,1.000000,0.999998,0.999862,0.999827
189,b0ee5d588d22,27,random_over_sampler,200,6,0.10,5,1.0,0.999953,0.999834,0.999827,0.999831,1.000000,0.999997,0.999862,0.999827
190,b0ee5d588d22,32,random_over_sampler,200,6,0.10,5,1.0,0.999956,0.999835,0.999839,0.999837,1.000000,0.999999,0.999871,0.999839
191,b0ee5d588d22,59,random_over_sampler,200,6,0.10,5,1.0,0.999953,0.999818,0.999827,0.999823,1.000000,0.999997,0.999862,0.999827

,configuration_id,seed,fold,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f3ea52a0aee0,27,1,passthrough,100,3,0.05,1,0.8,0.999725,0.999027,0.999071,0.999048,0.999996,0.999923,0.999199,0.999071
1,f3ea52a0aee0,27,2,passthrough,100,3,0.05,1,0.8,0.999756,0.999231,0.999175,0.999202,0.999998,0.999978,0.999288,0.999175
2,f3ea52a0aee0,27,3,passthrough,100,3,0.05,1,0.8,0.999898,0.999937,0.999638,0.999787,1.000000,0.999998,0.999703,0.999638
3,f3ea52a0aee0,32,1,passthrough,100,3,0.05,1,0.8,0.999797,0.999401,0.999312,0.999356,0.999999,0.999993,0.999407,0.999312
4,f3ea52a0aee0,32,2,passthrough,100,3,0.05,1,0.8,0.999837,0.999625,0.999448,0.999536,1.000000,0.999995,0.999525,0.999448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,b0ee5d588d22,32,2,random_over_sampler,200,6,0.10,5,1.0,0.999969,0.999893,0.999896,0.999895,1.000000,1.000000,0.999911,0.999896
572,b0ee5d588d22,32,3,random_over_sampler,200,6,0.10,5,1.0,0.999929,0.999720,0.999723,0.999722,1.000000,0.999997,0.999792,0.999723
573,b0ee5d588d22,59,1,random_over_sampler,200,6,0.10,5,1.0,0.999949,0.999789,0.999827,0.999808,1.000000,0.999998,0.999852,0.999827
574,b0ee5d588d22,59,2,random_over_sampler,200,6,0.10,5,1.0,0.999959,0.999841,0.999862,0.999851,1.000000,0.999994,0.999881,0.999862
575,b0ee5d588d22,59,3,random_over_sampler,200,6,0.10,5,1.0,0.999949,0.999824,0.999792,0.999808,1.000000,1.000000,0.999852,0.999792

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,17edbfb766e1,passthrough,200,6,0.1,1,0.8,0.99997 ± 0.00000,0.99991 ± 0.00002,0.99989 ± 0.00001,0.99990 ± 0.00001,1.00000 ± 0.00000,1.00000 ± 0.00000,0.99991 ± 0.00001,0.99989 ± 0.00001